apiVersion: v1
kind: ConfigMap
metadata:
  name: html-configmap
data:
  index.html: |
    <html>
      <head>
        <meta charset="UTF-8">
        <title>It is a sad hamster</title>
        <style>
           body {
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
                margin: 0;
                font-family: 'Arial', sans-serif;
                background-color: #fc88a3;
                height: 100vh;
           }
           h1 {
                color: white;
           }
      </style>
      </head>
      <body>
        <h1>Wanna see a sad hamster?</h1>
        <h1> ʢٛ•ꇵٛ•ʡ </h1>
        <h1> Here it is (hihihaha в этот раз без картинки it's a prank)</h1>
      </body>
    </html>
