replicaCount: 1 

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.26.2"

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30008

volumes:
  name: html-volume2
  configMapName: configmap
  mountPath: /usr/share/nginx/html

htmlConfigMapData: |
  <html><body><h1>meow meow meow meow (we've been doing this upgrade for the millionth time and we're on the verge of tears rn)</h1></body></html>
