name: Bad CI/CD Workflow

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: First step
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          cd lab_4 && npm install

      - name: Run tests
        run: cd lab_4 && npm test || echo "Если тесты провалились, мы продолжим))"

      - name: Deploy application
        env:
          APP_SECRET: "my_super_secret"
        run: |
          echo "Деплоим..."
          echo "Задеплоили!" 
